function manifest = required_package_files()
%REQUIRED_PACKAGE_FILES Required entry points and MATLAB functions.
manifest = struct();
manifest.EntryPoints = { ...
    'RUN_PACKAGE_AUDIT.m'; ...
    'RUN_OFFLINE_SELFTEST.m'; ...
    'RUN_PUBLIC_QUICK.m'; ...
    'RUN_PUBLIC_FULL.m'; ...
    'RUN_OPEN_NGS_PROJECT_PAGES.m'};
manifest.FunctionFiles = { ...
    'build_network.m'; ...
    'calibrate_public_covariance.m'; ...
    'canonicalize_station_pairs.m'; ...
    'clean_and_collapse_observations.m'; ...
    'compute_path_statistics.m'; ...
    'convert_height_to_m.m'; ...
    'convert_length_to_km.m'; ...
    'evaluate_public_methods.m'; ...
    'figure_readability_audit.m'; ...
    'find_disjoint_paths.m'; ...
    'find_public_validation_cases.m'; ...
    'generate_public_figures.m'; ...
    'get_alias_value.m'; ...
    'hash_file_sha256.m'; ...
    'infer_project_id.m'; ...
    'log_message.m'; ...
    'make_json_compatible.m'; ...
    'method_coefficients_public.m'; ...
    'minimax_route_weights.m'; ...
    'normalize_field_name.m'; ...
    'open_ngs_project_pages.m'; ...
    'package_integrity_audit.m'; ...
    'paired_method_bootstrap.m'; ...
    'parse_leveling_files.m'; ...
    'parse_ngs_benchmark_geojson.m'; ...
    'parse_ngs_observation_geojson.m'; ...
    'parse_tabular_observations.m'; ...
    'public_scale_sensitivity.m'; ...
    'public_validation_config.m'; ...
    'public_validation_unit_tests.m'; ...
    'read_primary_function_name.m'; ...
    'required_package_files.m'; ...
    'resolve_input_files.m'; ...
    'robust_nnls2.m'; ...
    'run_public_validation.m'; ...
    'safe_mkdir.m'; ...
    'save_figure_bundle.m'; ...
    'simple_percentile.m'; ...
    'split_public_cases.m'; ...
    'summarize_method_table.m'; ...
    'timestamp_string.m'; ...
    'value_to_double.m'; ...
    'value_to_string.m'; ...
    'write_json_file.m'; ...
    'write_text_file.m'};
manifest.DataFiles = { ...
    fullfile('data','example','offline_fixture_observations.csv'); ...
    fullfile('data','config','ngs_projects.csv'); ...
    fullfile('data','raw','ngs','README.txt')};
end
